### PR TITLE
added two sections in template files, but wait for backend to add pin…

### PR DESCRIPTION
**Pull request by corincewang**
Estimate hour: 9hours.
Workdone: Added skeleton on 2 sections for pinned and unpinned posts in the topic.tpl. Also added a few back-end fields to test. Currently all the posts are in 2 sections (but can't reveal pinned post at the top), though not what I expected but at least have progress. 
Testdone: Since pin feature is not yet implemented, I used bookmark to test the 2 sections. Also tested some posts by changing their features in developing mode.

### CODE REVIEW

**Review by Skadeven — COMMENTED** [review]
tpl change successfully achieve your goal. Appreciate your contribution to both front end and back end.

**Comment by GabrielAguirre1** [comment]
@corincewang Do you know why all these tests are failing? Or is this PR no longer relevant?

**Comment by corincewang** [comment]
> @corincewang Do you know why all these tests are failing? Or is this PR no longer relevant?

I am not vey sure. I only modified two files but I am not sure why these are failing. Even lint fails. But I will keep work on fixing them.

**Review by viviannna — COMMENTED** [review]
Not entirely sure why there are so many extra files (topic_2024...js and data_2024...js) that (seem?) to be duplicates. I'm assuming they're mock data examples of what the server would look like? Maybe it would be better to have them in a separate commit because it takes a while to find the actual code files changed. 

Otherwise, demo in class looked good! We should meet at some point to try to figure out how to combine our features.

**Comment by GabrielAguirre1** [comment]
Sorry guys. We need to merge these before midnight tonight, so I'm guessing your code will not work because I had to change "pinned" to "important" in one place. This sort of change was needed for when we merge the two systems in any case, but just know that immediately the UI will not work, but that switch from "pinned" --> "important" should be all we have to do to get it up running.

**Pull request merged**
