### PR TITLE
Add the button for instructors to pin post

### LINKED ISSUE #3: Button for instructors to mark a post as important/unimportant
Estimated Effort: 8-10 hours
Need to learn TypeScript, find the correct files, make it look nice
Criteria: There is a button attached to posts that can be clicked or unclicked

### PR DESCRIPTION
**Pull request by Skadeven**
resolves #3 
Effort: 16 hours
Criteria: There is a button attached to posts that can be clicked or unclicked
Progress: Currently I modified hundreds of code in both public and src folders with added assertion and typescript translations to the relevant javascript files. And now the website can show a button of pin in the drop down list of both posts and replies for instructor account. Now when clicking on it, it now doesn't show any change in the backend code because this function is dependent on issue #2

### CODE REVIEW

**Review by corincewang — COMMENTED** [review]
I see the button function is already added successfully. And I see there are some backend properties added for testing purpose

**Comment by GabrielAguirre1** [comment]
Yup, looks pretty good to me. I recommend that next time you try to make your PRs smaller, so there more digestible, but overall the code looks good. Particularly I like the comments you write, and it seems like you've conformed to the JS type checking.

**Review by viviannna — COMMENTED** [review]
Agree with the comment about smaller commits. Especially since you added so much code, some comments/description/smaller commits would be super helpful.

Looks like lots of good work was done to add the pin! Love the use of function headers.

**Comment by GabrielAguirre1** [comment]
Just resolved merge conflicts, I don't expect test cases to work because of this

**Pull request merged**
